import numpy as np
import cv2
import torch
from typing import Tuple, Union


def fast_image_blending(
    ori_frame: np.ndarray,
    res_frame: np.ndarray,
    face_box: Union[list, tuple],
    mask_array: np.ndarray,
    crop_box: Union[list, tuple],
) -> np.ndarray:
    """
    High-performance image blending optimized for real-time video generation.
    Replaces slow PIL roundtrips with direct NumPy/OpenCV slice operations.

    Args:
        ori_frame: Original full body/face frame (H, W, 3) in BGR format
        res_frame: Inpainted mouth/face patch generated by VAE decode (H_f, W_f, 3) in BGR
        face_box: (x, y, x1, y1) bounding box of face
        mask_array: (H_c, W_c) alpha blending mask in range [0, 255] or [0.0, 1.0]
        crop_box: (x_s, y_s, x_e, y_e) expanded crop bounding box
    """
    x, y, x1, y1 = face_box
    x_s, y_s, x_e, y_e = crop_box

    # Ensure bounds stay within image limits
    H, W, _ = ori_frame.shape
    x_s, y_s = max(0, x_s), max(0, y_s)
    x_e, y_e = min(W, x_e), min(H, y_e)

    # Crop the working region from the original frame
    crop_h = y_e - y_s
    crop_w = x_e - x_s
    if crop_h <= 0 or crop_w <= 0:
        return ori_frame

    # Clone the region to avoid modifying original array in-place
    working_patch = ori_frame[y_s:y_e, x_s:x_e].copy()

    # Target relative offsets in the crop box
    rx1 = max(0, x - x_s)
    ry1 = max(0, y - y_s)
    rx2 = min(crop_w, x1 - x_s)
    ry2 = min(crop_h, y1 - y_s)

    target_w = rx2 - rx1
    target_h = ry2 - ry1

    if target_w <= 0 or target_h <= 0:
        return ori_frame

    # Resize generated mouth patch to match face bounding box
    if res_frame.shape[0] != target_h or res_frame.shape[1] != target_w:
        res_patch = cv2.resize(res_frame, (target_w, target_h), interpolation=cv2.INTER_LINEAR)
    else:
        res_patch = res_frame

    # Paste resized mouth patch onto working patch
    working_patch[ry1:ry2, rx1:rx2] = res_patch

    # Prepare alpha mask
    if mask_array.shape[0] != crop_h or mask_array.shape[1] != crop_w:
        mask_resized = cv2.resize(mask_array, (crop_w, crop_h), interpolation=cv2.INTER_LINEAR)
    else:
        mask_resized = mask_array

    if mask_resized.dtype != np.float32:
        mask_norm = (mask_resized.astype(np.float32) / 255.0)[:, :, np.newaxis]
    else:
        mask_norm = mask_resized[:, :, np.newaxis] if mask_resized.ndim == 2 else mask_resized

    # Alpha blending: output = mask * working_patch + (1 - mask) * ori_patch
    ori_patch = ori_frame[y_s:y_e, x_s:x_e]
    blended_patch = (mask_norm * working_patch + (1.0 - mask_norm) * ori_patch).astype(np.uint8)

    # Place back onto output frame
    output_frame = ori_frame.copy()
    output_frame[y_s:y_e, x_s:x_e] = blended_patch
    return output_frame
